#!/usr/bin/env bash
# Whispy installer. Desktop hotkeys get a shell wrapper that pip never overwrites.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${PREFIX:-$HOME/.local}"
BIN_DIR="$PREFIX/bin"
HOTKEY_BIN="$BIN_DIR/whispy-hotkey"
WHISPY_BIN="$BIN_DIR/whispy"
WRAPPER_SRC="$SCRIPT_DIR/scripts/whispy-hotkey.sh"
UNIT_SRC="$SCRIPT_DIR/packaging/whispy-ptt.service"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"

echo "→ Installing whispy"

mkdir -p "$BIN_DIR"

if command -v pip >/dev/null 2>&1; then
    pip install -e "$SCRIPT_DIR" --user --quiet --break-system-packages 2>/dev/null \
        || pip install -e "$SCRIPT_DIR" --user --quiet
elif command -v uv >/dev/null 2>&1; then
    uv pip install -e "$SCRIPT_DIR" --system 2>/dev/null \
        || uv tool install -e "$SCRIPT_DIR" --force
else
    echo "pip or uv required" >&2
    exit 1
fi

# Hotkey wrapper lives at its own path so pip upgrades never clobber it
install -m 755 "$WRAPPER_SRC" "$HOTKEY_BIN"
if [[ ! -x "$WHISPY_BIN" ]]; then
    ln -sf "$HOTKEY_BIN" "$WHISPY_BIN"
fi

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/whispy"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/whispy"
APP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
mkdir -p "$CONFIG_DIR" "$DATA_DIR/models" "$APP_DIR" "$UNIT_DIR"

if [[ ! -f "$CONFIG_DIR/whispy.conf" ]]; then
    cat > "$CONFIG_DIR/whispy.conf" <<'CONF'
# Whispy — every key is optional. Edit by hand, or run: whispy gui
PROVIDER=local                  # local = offline. `whispy providers` lists them all
WHISPER_MODEL=                  # empty = auto-detect
WHISPER_LANGUAGE=en             # en, it, … ("auto" to detect)
WHISPER_THREADS=8
AUTOPASTE=1                     # 0 = clipboard only
PTT_KEY=META+F12                # push-to-talk key
NOTIFY_LEVEL=normal             # normal | quiet | off
MAX_RECORD_SECONDS=8            # toggle safety net
CONF
    echo "→ Config: $CONFIG_DIR/whispy.conf"
fi

# Desktop entry: generated by whispy itself (whispy/desktop.py), because the
# right-click menu lists only the providers you can actually use — so it has to
# be rebuilt whenever a key is saved, not frozen at install time.
rm -f "$APP_DIR/whispy-tray.desktop"
python3 -m whispy desktop || echo "  ! could not write the desktop entry"

# --- push-to-talk unit ---
sed -e "s|__WHISPY_BIN__|$WHISPY_BIN|g" -e "s|__BIN_DIR__|$BIN_DIR|g" \
    "$UNIT_SRC" > "$UNIT_DIR/whispy-ptt.service"
systemctl --user daemon-reload 2>/dev/null || true
echo "→ Unit: $UNIT_DIR/whispy-ptt.service"

PTT_ACTIVE=0
systemctl --user is-enabled whispy-ptt.service >/dev/null 2>&1 && PTT_ACTIVE=1

# --- KDE: bind the toggle hotkey ONLY when push-to-talk isn't in charge ---
# Both on the same key would fire two recordings per press.
KGLOB="${XDG_CONFIG_HOME:-$HOME/.config}/kglobalshortcutsrc"
if [[ -f "$KGLOB" && "$PTT_ACTIVE" -eq 0 ]]; then
    KHOT="${XDG_CONFIG_HOME:-$HOME/.config}/khotkeysrc"
    if [[ -f "$KHOT" ]]; then
        # khotkeys + kglobalaccel on the same key = double fire
        sed -i 's/^Enabled=true$/Enabled=false/' "$KHOT" 2>/dev/null || true
        sed -i "s|CommandURL=.*whispy.*|CommandURL=$HOTKEY_BIN|g" "$KHOT" 2>/dev/null || true
    fi

    python3 - "$KGLOB" <<'PY'
import re
import sys
from pathlib import Path

p = Path(sys.argv[1])
text = p.read_text(encoding="utf-8")
# release Meta+F12 from the older whisper-toggle entry, if present
text = re.sub(r"(\[services\]\[whisper-toggle\.desktop\]\n)_launch=.*", r"\1_launch=none", text)
if "[services][whispy.desktop]" not in text:
    text = text.rstrip() + "\n\n[services][whispy.desktop]\n_launch=Meta+F12\n"
else:
    text = re.sub(
        r"(\[services\]\[whispy\.desktop\]\n)_launch=.*", r"\1_launch=Meta+F12", text, count=1
    )
p.write_text(text, encoding="utf-8")
print("→ KDE: Meta+F12 → toggle")
PY
    systemctl --user try-restart plasma-kglobalaccel.service 2>/dev/null || true
elif [[ "$PTT_ACTIVE" -eq 1 ]]; then
    echo "→ push-to-talk is enabled: leaving desktop shortcuts untouched"
fi

echo ""
echo "System tools:"
for tool in whisper-cli arecord wl-copy ydotool notify-send python3; do
    if command -v "$tool" >/dev/null 2>&1; then
        echo "  ✓ $tool"
    else
        echo "  · $tool (MISSING)"
    fi
done
python3 -c "import evdev" 2>/dev/null \
    && echo "  ✓ python-evdev" \
    || echo "  · python-evdev (MISSING — required for push-to-talk)"

if ! id -nG "$USER" | grep -qw input; then
    echo ""
    echo "  ! You are not in the 'input' group — push-to-talk cannot read the keyboard."
    echo "    sudo usermod -aG input $USER    # then log out and back in"
fi

# --- model check ---
# The most common "I installed it and nothing happens": there is no model on
# disk. Whispy can't transcribe without one, so say so here rather than let it
# fail on the first key press.
HAVE_MODEL=0
for m in "$DATA_DIR/models/ggml-large-v3-turbo.bin" \
         "$DATA_DIR/models/ggml-base.bin" \
         "$HOME/.local/share/whisper-toggle/models/ggml-large-v3-turbo.bin" \
         "$HOME/.local/share/whisper-toggle/models/ggml-base.bin"; do
    [[ -f "$m" ]] && { HAVE_MODEL=1; echo ""; echo "  ✓ model: $m"; break; }
done

if [[ "$HAVE_MODEL" -eq 0 ]]; then
    echo ""
    echo "  ! No model found — whispy cannot transcribe yet. Download one:"
    echo ""
    echo "    # small and fast, ~150 MB — fine to start with"
    echo "    curl -L --create-dirs -o $DATA_DIR/models/ggml-base.bin \\"
    echo "      https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin"
    echo ""
    echo "    # much more accurate, ~1.6 GB — recommended if you have a GPU"
    echo "    curl -L --create-dirs -o $DATA_DIR/models/ggml-large-v3-turbo.bin \\"
    echo "      https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin"
fi

echo ""
echo "✔ Installed"
echo ""
echo "  1. Open the control panel to pick a provider and check your setup:"
echo "       whispy gui"
echo ""
echo "  2. Push-to-talk (recommended) — hold the key, speak, release:"
echo "       systemctl --user enable --now whispy-ptt"
echo ""
echo "     Toggle — press once to start, press again to transcribe:"
echo "       bind a shortcut to $WHISPY_BIN   (absolute path required)"
echo ""
echo "  Backends: whispy providers"
echo "  Logs:     tail -f /tmp/whispy.log"
echo "  Tests:    pip install -e '.[dev,ptt]' && pytest -q"
